apiVersion: v1
kind: Secret
metadata:
 name: registry-pull-secret
data:
 .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJiYmJhY3IuYXp1cmVjci5pbyI6IHt9LAoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7fQoJfSwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiLAoJImN1cnJlbnRDb250ZXh0IjogImRlc2t0b3AtbGludXgiCn0=
type: kubernetes.io/dockerconfigjson