name: My Workflow

on:
  push:
    branches:
      - minikube

jobs:
  run-helm:
    runs-on: my-mac

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Another Step
        run: echo "This is another step"
        
      - name: Helm Deployment
        run: |
          kubectl config get-contexts
          helm upgrade --install my-cherry-chart buildchart/