name: My Workflow

on:
  push:
    branches:
      - minikube
    paths:
      - .github/workflows/helm-deploy.yaml

env:
  PackageVersion: 1.0.0
  docker_repo: pongu

jobs:
  run-helm:
    runs-on: my-mac

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Another Step
      #   run: |
      #    docker login -u ${{ env.docker_repo }} -p ${{ secrets.MY_DOCKER_PASSWORD }}
        
      - name: Helm Deployment
        run: |
          kubectl config get-contexts
          helm upgrade --install my-cherry-chart buildchart/ \
          --set image.tag=${{env.PackageVersion}} \
          --set image.repository=${{env.docker_repo}} \
          --values buildchart/values-global.yaml \
          --values buildchart/values-local.yaml 