name: Helm build

on:
  push:
    branches:
      - minikube
    paths:
      - .github/workflows/helm-build.yaml

env:
  PackageVersion: 1.0.0
  docker_repo: pongu

jobs:
  run-helm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: helm build chart
        run: | 
          #### HELM ####
          mkdir azure-helm-repository
          
          helm repo add common https://charts.helm.sh/incubator
          helm dependency update buildchart
          helm package ./buildchart
          
          cp ./buildchart-0.1.0.tgz ./azure-helm-repository/
          helm repo index ./azure-helm-repository

          az storage blob upload-batch --overwrite --account-name muzikzzacc \
          --destination charts \
          --source ./azure-helm-repository

          # az storage blob upload \
          # --file "./buildchart-0.1.0.tgz" \
          # --file "./index.yaml" \
          # --container-name charts \
          # --account-name muzikzzacc \
          # --auth-mode login

